[package]
name = "magicentry"
version = "0.8.10"
edition = "2024"

[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["."]

[workspace.dependencies]
maud = { version = "0.27", features = ["axum"] }
serde_qs = { version = "1.1", features = ["axum"] }

chrono = { version = "0.4", features = ["serde"] }
derive_more = { version = "2.1", features = ["display", "error"] }
duration-str = "0.21"
formatx = "0.4"
futures = "0.3"
hex = "0.4.3"
lettre = { version = "0.11", default-features = false, features = [
  "builder",
  "pool",
  "rustls-tls",
  "smtp-transport",
  "tokio1-rustls-tls",
] }
md5 = "0.8"
notify = "8"
rand = "0.10"
reqwest = { version = "0.13", default-features = false, features = [
  "default-tls",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sha2 = "0.11"
sqlx = { version = "0.9", features = [
  "all-databases",
  "chrono",
  "json",
  "migrate",
  "runtime-tokio",
  "tls-rustls",
  "uuid"
] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }
url = { version = "2", features = ["serde"] }
urlencoding = "2.1"
uuid = { version = "1.26", features = ["serde", "v4"] }
webauthn-rs = { version = "0.5", features = ["danger-allow-state-serialisation"] }

# Dependency of webauthn-rs that needs to be vendored
openssl = { version = "0.10", features = ["vendored"] }

anyhow = "1.0"
async-trait = "0.1"
base64 = "0.23"
flate2 = "1.1"
jsonwebtoken = { version = "11", default-features = false, features = [
  "rust_crypto"
] }
quick-xml = { version = "0.42", features = ["async-tokio", "serialize"] }
rsa = { version = "0.9", features = ["getrandom", "sha2"] }
thiserror = "2.0"

arc-swap = "1.9"
axum = { version = "0.8", features = ["http2", "macros", "tokio"] }
axum-extra = { version = "0.12", features = [
  "cookie",
  "form",
  "query",
  "typed-header",
  "typed-routing"
] }
headers = "0.4"
k8s-openapi = { version = "0.28", features = ["earliest"] }
kube = { version = "4.2", features = ["derive", "runtime"] }
tower-http = { version = "0.7", features = ["fs", "trace"] }

# dev deps
actix-http = "3.13"
axum-test = { version = "21", features = ["reqwest", "typed-routing"] }

criterion = { version = "0.8", features = ["async_tokio"] }
glob = "0.3"
# Use Hurl as a library to run E2E HTTP specs
# We intentionally put this under dev-dependencies so it's only pulled for tests
hurl = "*"
hurl_core = "*"
scraper = "0.27"
tempfile = "3.27"
tiny_http = "0.12"

[[bench]]
harness = false
name = "authurl_status"

[dependencies]
anyhow.workspace = true
arc-swap.workspace = true
async-trait.workspace = true
axum.workspace = true
axum-extra.workspace = true
base64.workspace = true
chrono.workspace = true
derive_more.workspace = true
duration-str.workspace = true
flate2.workspace = true
formatx.workspace = true
futures.workspace = true
headers.workspace = true
hex.workspace = true
jsonwebtoken.workspace = true
lettre.workspace = true
maud.workspace = true
md5.workspace = true
notify.workspace = true
openssl.workspace = true
quick-xml.workspace = true
rand.workspace = true
reqwest.workspace = true
rsa.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_qs.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
urlencoding.workspace = true
uuid.workspace = true
webauthn-rs.workspace = true

k8s-openapi = { workspace = true, optional = true }
kube = { workspace = true, optional = true }

[dev-dependencies]
actix-http.workspace = true
axum-test.workspace = true

criterion.workspace = true
glob.workspace = true
hurl.workspace = true
hurl_core.workspace = true
scraper.workspace = true
tempfile.workspace = true
tiny_http.workspace = true

[features]
default = []
kube = ["dep:k8s-openapi", "dep:kube"]

[lints.clippy]
enum_glob_use = "deny"
option_if_let_else = "allow"
# pedantic = "deny"
# nursery = "deny"
# unwrap_used = "deny"

[lints.rust]
unsafe_code = "forbid"

[profile.release]
opt-level = 3
strip = "symbols"
lto = true
panic = "abort"
codegen-units = 1
