FROM rust:1 AS builder
WORKDIR /app

RUN chown -R 1000:1000 /app
RUN apt-get update && apt-get install -y \
	gcc-aarch64-linux-gnu \
	make \
	pkg-config \
	libclang-dev \
	libssl-dev \
	libxml2-dev \
	libfindbin-libs-perl

USER 1000:1000

CMD ["cargo", "run"]
