FROM node:alpine as frontend

WORKDIR /usr/src/app

COPY static static
COPY *.js *.json ./
RUN npm install --dev
RUN npm run build

FROM rust:alpine as builder

RUN apk add --no-cache musl-dev tcpdump

WORKDIR /usr/src/app

RUN cargo init --vcs none --bin
COPY Cargo.toml Cargo.lock ./
# Enable mount-type caching and dependency caching to be compatible with github actions
RUN --mount=type=cache,target=/usr/local/cargo/git,id=just-passwordless-cargo-git-cache \
	--mount=type=cache,target=/usr/local/cargo/registry,id=just-passwordless-cargo-registry-cache \
	--mount=type=cache,target=/usr/src/app/target,id=just-passwordless-cargo-target-cache \
	cargo build && \
	rm target/debug/deps/just_passwordless*

COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/git,id=just-passwordless-cargo-git-cache \
	--mount=type=cache,target=/usr/local/cargo/registry,id=just-passwordless-cargo-registry-cache \
	--mount=type=cache,target=/usr/src/app/target,id=just-passwordless-cargo-target-cache \
	cargo build && \
	cp target/debug/just-passwordless /usr/local/bin/

ENV CONFIG_FILE=/config.yaml
ENV RUST_LOG=info

EXPOSE 8080/tcp
CMD ["/usr/local/bin/just-passwordless"]
