FROM node:alpine as frontend

WORKDIR /usr/src/app

COPY static static
COPY *.js *.json ./
RUN --mount=type=cache,target=node_modules,id=magicentry-node-modules \
	npm install --include=dev
RUN npm run build

FROM rust as builder

WORKDIR /usr/src/app

RUN cargo init --vcs none --bin
COPY Cargo.toml Cargo.lock ./
COPY .cargo .cargo
RUN --mount=type=cache,target=/usr/local/cargo/git,id=magicentry-cargo-git-cache \
	--mount=type=cache,target=/usr/local/cargo/registry,id=magicentry-cargo-registry-cache \
	--mount=type=cache,target=/usr/src/app/target,id=magicentry-cargo-target-cache \
	cargo build --all-features && \
	rm target/debug/deps/magicentry*

COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/git,id=magicentry-cargo-git-cache \
	--mount=type=cache,target=/usr/local/cargo/registry,id=magicentry-cargo-registry-cache \
	--mount=type=cache,target=/usr/src/app/target,id=magicentry-cargo-target-cache \
	cargo build --all-features && \
	cp target/debug/magicentry /usr/local/bin/

ENV CONFIG_FILE=/config.yaml
ENV RUST_LOG=info

EXPOSE 8080/tcp
CMD ["/usr/local/bin/magicentry"]
