---

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
  labels:
    # .Chart.Version makes fluxcd unable to apply the chart
    chart: "{{ .Chart.Name }}"
data:
  config.yaml: {{ .Values.config | toYaml | quote }}
