CREATE TABLE sessions (
	session_id TEXT PRIMARY KEY,
	email TEXT NOT NULL,
	expires_at TIMESTAMP NOT NULL
) WITHOUT ROWID;

CREATE TABLE links (
	magic TEXT PRIMARY KEY,
	email TEXT NOT NULL,
	expires_at TIMESTAMP NOT NULL
) WITHOUT ROWID;

CREATE TABLE config (
	key TEXT PRIMARY KEY,
	value TEXT
) WITHOUT ROWID;
